function ret = shell(n,V,sampleSize,seed)
%
% n is number of candidates
% V is number of voters
% w is the weight vector for tallyBorda
% sampleSize is the size of the desired sample of preference schedules
% seed is for the rng
%
% This method takes in parameters and generates an appropriate sample
% of preference schedules, which it then passes to the bordaTally and
% pluralityTally methods. It passes the outcome vectors generated by
% bordaTally and pluralityTally to compare and returns the result
sample = generateSample(V,n,seed,sampleSize);
[num cha fin tal] = copelandTally(sample);
count = 0;
for i=1:length(fin)
    count = count + isequal(fin(i,:),[2.5 1.5 0 2]);
    count = count + isequal(fin(i,:),[2.5 0.5 1 2]);
    count = count + isequal(fin(i,:),[2.5 1 0.5 2]);
    count = count + isequal(fin(i,:),[2.5 2 0 1.5]);
    count = count + isequal(fin(i,:),[2.5 1 1 1.5]);
    count = count + isequal(fin(i,:),[2.5 1.5 0.5 1.5]);
    count = count + isequal(fin(i,:),[2.5 1 1.5 1]);
    count = count + isequal(fin(i,:),[2.5 1.5 1.5 0.5]);
    count = count + isequal(fin(i,:),[2.5 1.5 2 0]);
    count = count + isequal(fin(i,:),[2.5 0.5 2 1]);
    count = count + isequal(fin(i,:),[2.5 1 2 0.5]);
    count = count + isequal(fin(i,:),[2.5 1.5 1 1.5]);
    count = count + isequal(fin(i,:),[2.5 1 1.5 1.5]);
    count = count + isequal(fin(i,:),[2.5 1.5 1.5 1]);
end
ret = count;
end